import { AlertTriangle } from 'lucide-react';

const Disclaimer = () => {
  return (
    <div className="min-h-screen bg-soft-white py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h1 className="text-3xl md:text-4xl font-bold text-deep-blue mb-4">Disclaimer</h1>
          <p className="text-xl text-gray-600">
            Important information about the use of our services
          </p>
        </div>

        <div className="bg-white rounded-xl shadow-lg p-8 border border-gray-200">
          <div className="flex items-center gap-3 mb-6">
            <AlertTriangle className="w-8 h-8 text-gold-500" />
            <h2 className="text-2xl font-bold text-deep-blue">Legal Disclaimer</h2>
          </div>

          <div className="prose max-w-none">
            <p className="text-gray-700 mb-6">
              This disclaimer ("Disclaimer") is an agreement between LexEase ("us", "we" or "our") 
              and you ("User", "you" or "your"). This Disclaimer sets forth the general guidelines, 
              terms and conditions that govern your use of the LexEase website and any of its products 
              or services (collectively, "Website" or "Services").
            </p>

            <h3 className="text-xl font-semibold text-deep-blue mt-8 mb-4">Content Accuracy</h3>
            <p className="text-gray-700 mb-4">
              While we strive to ensure that the information on this website is correct, we do not 
              warrant the accuracy, completeness, or usefulness of this information. Any reliance 
              you place on such information is strictly at your own risk. We disclaim all liability 
              and responsibility arising from any reliance placed on such materials by you or any 
              other visitor to the website, or by anyone who may be informed of any of its contents.
            </p>

            <h3 className="text-xl font-semibold text-deep-blue mt-8 mb-4">No Legal Advice</h3>
            <p className="text-gray-700 mb-4">
              The information and documents provided by LexEase are for general informational 
              purposes only and do not constitute legal advice. We are not a law firm and do not 
              provide legal advice or recommendations. Your use of the website and services does 
              not create an attorney-client relationship between you and LexEase.
            </p>

            <h3 className="text-xl font-semibold text-deep-blue mt-8 mb-4">Generated Content</h3>
            <p className="text-gray-700 mb-4">
              Documents generated by our system are based on the information you provide and 
              standard legal templates. While we aim to provide accurate and helpful content, 
              automatically generated documents may not be suitable for all situations and should be 
              reviewed by a qualified legal professional before use, especially for complex legal matters.
            </p>

            <h3 className="text-xl font-semibold text-deep-blue mt-8 mb-4">Limitation of Liability</h3>
            <p className="text-gray-700 mb-4">
              In no event shall LexEase, nor its directors, employees, partners, agents, suppliers, 
              or affiliates, be liable for any indirect, incidental, special, consequential or 
              punitive damages, including without limitation, loss of profits, data, use, 
              goodwill, or other intangible losses, resulting from (i) your access to or use of 
              or inability to access or use the service; (ii) any conduct or content of any third 
              party on the service; (iii) any content obtained from the service; and (iv) unauthorized 
              access, use or alteration of your transmissions or content, whether based on warranty, 
              contract, tort (including negligence) or any other legal theory, whether or not we have 
              been informed of the possibility of such damage.
            </p>

            <h3 className="text-xl font-semibold text-deep-blue mt-8 mb-4">External Links</h3>
            <p className="text-gray-700 mb-4">
              Our website may contain links to external websites that are not provided or maintained 
              by or in any way affiliated with us. Please note that we do not guarantee the accuracy, 
              relevance, timeliness, or completeness of any information on these external websites.
            </p>

            <h3 className="text-xl font-semibold text-deep-blue mt-8 mb-4">Changes to This Disclaimer</h3>
            <p className="text-gray-700 mb-4">
              We reserve the right to modify this Disclaimer relating to the Website or Services at 
              any time, effective upon posting of an updated version of this Disclaimer on the 
              Website. Continued use of the Website after any such changes shall constitute your 
              consent to such changes.
            </p>

            <div className="bg-gold-50 border-l-4 border-gold-500 p-4 mt-8">
              <div className="flex">
                <div className="flex-shrink-0">
                  <AlertTriangle className="h-5 w-5 text-gold-500" />
                </div>
                <div className="ml-3">
                  <p className="text-sm text-gold-700">
                    <strong>Important:</strong> For complex legal matters or situations with significant 
                    financial or legal implications, we strongly recommend consulting with a qualified 
                    legal professional who is licensed to practice law in your jurisdiction.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
