import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Download, ArrowLeft, Printer } from 'lucide-react';

const RENT_AGREEMENT_TEMPLATE = `
<div style="
  font-family: 'Times New Roman', serif; 
  padding: 40px; 
  line-height: 1.8; 
  color: #000;
  max-width: 800px; 
  margin: 0 auto; 
  text-align: justify;
  background: white;
">
  <h2 style="text-align: center; text-transform: uppercase; margin-bottom: 30px; text-decoration: underline;">Rent Agreement</h2>
  
  <p>This Rent Agreement is made and executed on this <strong>{{currentDate}}</strong> at <strong>{{city}}</strong>;</p>
  
  <h4 style="margin-top: 30px; text-align: center;">BETWEEN</h4>
  
  <p><strong>{{landlordName}}</strong>, residing at {{landlordAddress}} (hereinafter referred to as the <strong>"LESSOR"</strong>, which expression shall unless repugnant to the context mean and include his/her heirs, successors, executors, and legal representatives) of the ONE PART.</p>
  
  <h4 style="margin-top: 20px; text-align: center;">AND</h4>
  
  <p><strong>{{tenantName}}</strong>, residing at {{tenantAddress}} (hereinafter referred to as the <strong>"LESSEE"</strong>, which expression shall unless repugnant to the context mean and include his/her heirs, successors, executors, and legal representatives) of the OTHER PART.</p>
  
  <p style="margin-top: 20px;">WHEREAS the Lessor is the absolute owner and in possession of the property bearing No. <strong>{{propertyAddress}}</strong> (hereinafter referred to as the "Said Premises").</p>
  
  <p>AND WHEREAS the Lessee has approached the Lessor for taking the said premises on rent for a temporary period of <strong>{{duration}}</strong> months, and the Lessor has agreed to let out the said premises on the following terms and conditions:</p>
  
  <h4 style="margin-top: 30px; text-align: left; text-decoration: underline;">NOW THIS AGREEMENT WITNESSETH AS UNDER:</h4>
  
  <ol style="padding-left: 20px; margin-top: 10px;">
    <li style="margin-bottom: 10px;">The Lessee shall pay a monthly rent of <strong>₹{{rentAmount}}/-</strong> (Rupees {{rentAmount}} only) per month to the Lessor on or before the 5th day of every English calendar month.</li>
    
    <li style="margin-bottom: 10px;">The Lessee has paid an interest-free Security Deposit of <strong>₹{{depositAmount}}/-</strong> to the Lessor, which shall be refundable at the time of vacating the premises after deducting any dues or damages.</li>
    
    <li style="margin-bottom: 10px;">The lease period shall commence from <strong>{{startDate}}</strong> and shall be valid for a period of <strong>{{duration}}</strong> months, expiring on <strong>{{endDate}}</strong>.</li>
    
    <li style="margin-bottom: 10px;">The Lessee shall pay specific electricity and water charges as per the actual bills generated by the concerned authorities.</li>
    
    <li style="margin-bottom: 10px;">The Lessee shall use the premises for <strong>Residential Purposes Only</strong> and shall not carry out any illegal or commercial activities.</li>
    
    <li style="margin-bottom: 10px;">The Lessee shall not sublet, assign, or part with the possession of the said premises to any third party under any circumstances.</li>
    
    <li style="margin-bottom: 10px;">The Lessor or his authorized agents shall have the right to inspect the premises at reasonable times with prior notice.</li>
  </ol>

  <p style="margin-top: 40px;">IN WITNESS WHEREOF, the parties hereto have signed this Agreement on the day, month, and year first above written in the presence of the following witnesses:</p>
  
  <div style="margin-top: 60px; display: flex; justify-content: space-between; page-break-inside: avoid;">
    <div style="text-align: center; width: 40%;">
      <div style="border-top: 1px solid #000; padding-top: 10px;"><strong>Signature of LESSOR</strong></div>
      <p>({{landlordName}})</p>
    </div>
    <div style="text-align: center; width: 40%;">
      <div style="border-top: 1px solid #000; padding-top: 10px;"><strong>Signature of LESSEE</strong></div>
      <p>({{tenantName}})</p>
    </div>
  </div>
</div>
`;

const INITIAL_FIELDS = {
  currentDate: new Date().toLocaleDateString(),
  city: '',
  landlordName: '',
  landlordAddress: '',
  tenantName: '',
  tenantAddress: '',
  propertyAddress: '',
  duration: '11',
  rentAmount: '',
  depositAmount: '',
  startDate: '',
  endDate: ''
};

const DocumentGenerator = () => {
  const [searchParams] = useSearchParams();
  const [formData, setFormData] = useState(INITIAL_FIELDS);
  const [previewHtml, setPreviewHtml] = useState(RENT_AGREEMENT_TEMPLATE);
  const [loading, setLoading] = useState(false);
  const [docType, setDocType] = useState('Rent Agreement');

  // Update preview whenever form data changes
  useEffect(() => {
    let html = RENT_AGREEMENT_TEMPLATE;
    Object.keys(formData).forEach(key => {
      const value = formData[key] || `<span style="color: #ccc;">[${key}]</span>`;
      // Global replace for the placeholder
      const regex = new RegExp(`{{${key}}}`, 'g');
      html = html.replace(regex, value);
    });
    setPreviewHtml(html);
  }, [formData]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const downloadPdf = async () => {
    setLoading(true);
    try {
      const response = await fetch('http://localhost:5000/api/generate-pdf', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ html: previewHtml })
      });

      if (!response.ok) throw new Error('Failed to generate PDF');

      // Create blob and download
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${docType.replace(/ /g, '_')}_${Date.now()}.pdf`; // Add timestamp to avoid caching/conflict
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Download error:', err);
      alert('Failed to download PDF. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex h-screen bg-gray-100 overflow-hidden">
      {/* LEFT SIDE: Form Inputs */}
      <div className="w-1/2 p-8 overflow-y-auto border-r border-gray-300 bg-white shadow-xl z-10">
        <div className="max-w-xl mx-auto">
          <div className="mb-8 flex items-center justify-between">
            <h1 className="text-2xl font-bold text-gray-800 flex items-center gap-2">
              <span className="p-2 bg-blue-100 text-blue-600 rounded-lg">
                📝
              </span>
              {docType} Generator
            </h1>
          </div>

          <div className="space-y-6">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-1">Date</label>
                <input
                  type="date"
                  name="currentDate"
                  value={formData.currentDate} // Note: input type=date needs YYYY-MM-DD
                  onChange={handleInputChange}
                  className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
                />
              </div>
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-1">City</label>
                <input
                  type="text"
                  name="city"
                  placeholder="e.g. Mumbai"
                  value={formData.city}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 transition-all"
                />
              </div>
            </div>

            <div className="bg-gray-50 p-4 rounded-xl border border-gray-200">
              <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4">Landlord Details</h3>
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Full Name</label>
                  <input
                    type="text"
                    name="landlordName"
                    value={formData.landlordName}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Address</label>
                  <textarea
                    name="landlordAddress"
                    value={formData.landlordAddress}
                    onChange={handleInputChange}
                    rows="2"
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500"
                  />
                </div>
              </div>
            </div>

            <div className="bg-gray-50 p-4 rounded-xl border border-gray-200">
              <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4">Tenant Details</h3>
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Full Name</label>
                  <input
                    type="text"
                    name="tenantName"
                    value={formData.tenantName}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Address</label>
                  <textarea
                    name="tenantAddress"
                    value={formData.tenantAddress}
                    onChange={handleInputChange}
                    rows="2"
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500"
                  />
                </div>
              </div>
            </div>

            <div className="bg-blue-50 p-4 rounded-xl border border-blue-100">
              <h3 className="text-sm font-bold text-blue-500 uppercase tracking-wider mb-4">Contract Terms</h3>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Rented Property Address</label>
                <textarea
                  name="propertyAddress"
                  value={formData.propertyAddress}
                  onChange={handleInputChange}
                  rows="2"
                  className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 mb-4"
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Monthly Rent (₹)</label>
                  <input
                    type="number"
                    name="rentAmount"
                    value={formData.rentAmount}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Security Deposit (₹)</label>
                  <input
                    type="number"
                    name="depositAmount"
                    value={formData.depositAmount}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Start Date</label>
                  <input
                    type="date"
                    name="startDate"
                    value={formData.startDate}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">End Date</label>
                  <input
                    type="date"
                    name="endDate"
                    value={formData.endDate}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* RIGHT SIDE: Live Preview */}
      <div className="w-1/2 bg-gray-200 p-8 flex flex-col h-screen">
        <div className="flex justify-between items-center mb-4 px-4">
          <h2 className="text-gray-700 font-bold uppercase tracking-widest text-sm flex items-center gap-2">
            <Printer size={16} /> Live Preview
          </h2>
          <button
            onClick={downloadPdf}
            disabled={loading}
            className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg font-semibold shadow-lg transition-all transform hover:scale-105 flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? (
              <span className="flex items-center gap-2">
                <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
                Generating PDF...
              </span>
            ) : (
              <>
                <Download size={18} /> Download Final PDF
              </>
            )}
          </button>
        </div>

        {/* A4 Paper Simulation */}
        <div className="flex-1 overflow-y-auto pb-20 flex justify-center">
          <div
            className="bg-white shadow-2xl p-12 min-h-[842px] w-[595px] transform transition-all origin-top scale-[0.8] md:scale-90 lg:scale-100"
            dangerouslySetInnerHTML={{ __html: previewHtml }}
          />
        </div>
      </div>
    </div>
  );
};

export default DocumentGenerator;
